=== kumara0230/XML-PROJEKAT-TIM15/back/a1/data/a1schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/a1" xmlns:a1="http://www.ftn.uns.ac.rs/a1">
    <xs:element name="Zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="a1:Podnosilac"/>
                <xs:element minOccurs="0" ref="a1:Autor"/>
                <xs:element minOccurs="0" ref="a1:Punomocnik"/>
                <xs:element ref="a1:Delo"/>
                <xs:element ref="a1:Popunjava_zavod"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Autor">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Lice" type="a1:TFizicko_lice"/>
                <xs:element minOccurs="0" name="Pseudonim_autora" nillable="false" type="xs:string"/>
                <xs:element minOccurs="0" name="Godina_smrti" nillable="false" type="xs:gYear"/>
                <xs:element minOccurs="1" name="Autor_anoniman" type="xs:boolean" default="false"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Punomocnik">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime" type="xs:string"/>
                <xs:element name="Prezime" type="xs:string"/>
                <xs:element ref="a1:Adresa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Delo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Naslov_dela" type="xs:string"/>
                <xs:element minOccurs="0" name="Alternativni_naslov" type="xs:string"/>
                <xs:element minOccurs="0" ref="a1:Delo_prerade"/>
                <xs:element name="Vrsta_autorskog_dela" type="xs:string"> </xs:element>
                <xs:element name="Forma_zapisa" type="xs:string"> </xs:element>
                <xs:element minOccurs="0" name="Delo_stvoreno_u_radnom_odnosu" type="xs:boolean"/>
                <xs:element minOccurs="0" name="Nacin_koriscenja_dela" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Delo_prerade">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Naslov_izvornog_dela" type="xs:string"/>
                <xs:element ref="a1:Autor"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Popunjava_zavod">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Opis_dela" type="xs:string"/>
                <xs:element name="Broj_prijave" type="xs:string"/>
                <xs:element name="Datum_podnosenja" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Ustanova">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv_ustanove">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element ref="a1:Adresa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podnosilac" type="a1:TLice"/>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj" type="xs:positiveInteger"/>
                <xs:element name="Mesto" type="xs:string"/>
                <xs:element name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="11000"/>
                            <xs:maxInclusive value="40000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Kontakt">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Broj_telefona" type="xs:string"/>
                <xs:element minOccurs="0" name="Email" type="xs:string"/>
                <xs:element minOccurs="0" name="Faks" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="a1:Adresa"/>
            <xs:element minOccurs="0" ref="a1:Kontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="a1:TLice">
                <xs:sequence>
                    <xs:element name="poslovno_ime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="a1:TLice">
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime" type="xs:string"/>
                    <xs:element name="Drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== kumara0230/XML-PROJEKAT-TIM15/back/users/data/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev xmlns="http://www.ftn.uns.ac.rs/a1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.ftn.uns.ac.rs/a1 a1schema.xsd">
    <Podnosilac xmlns:a1="http://www.ftn.uns.ac.rs/a1" xsi:type="a1:TFizicko_lice">
        <Adresa>
            <Ulica>Ulica0</Ulica>
            <Broj>50</Broj>
            <Mesto>Mesto0</Mesto>
            <Postanski_broj>25500</Postanski_broj>
        </Adresa>
        <Kontakt>
            <Broj_telefona>Broj_telefona0</Broj_telefona>
            <Email>Email0</Email>
            <Faks>Faks0</Faks>
        </Kontakt>
        <Ime>Ime0</Ime>
        <Prezime>Prezime0</Prezime>
        <Drzavljanstvo>Drzavljanstvo0</Drzavljanstvo>
    </Podnosilac>
    <Autor>
        <Lice>
            <Adresa>
                <Ulica>Ulica1</Ulica>
                <Broj>50</Broj>
                <Mesto>Mesto1</Mesto>
                <Postanski_broj>25500</Postanski_broj>
            </Adresa>
            <Kontakt>
                <Broj_telefona>Broj_telefona1</Broj_telefona>
                <Email>Email1</Email>
                <Faks>Faks1</Faks>
            </Kontakt>
            <Ime>Ime1</Ime>
            <Prezime>Prezime1</Prezime>
            <Drzavljanstvo>Drzavljanstvo1</Drzavljanstvo>
        </Lice>
        <Pseudonim_autora>Pseudonim_autora0</Pseudonim_autora>
        <Godina_smrti>2006</Godina_smrti>
        <Autor_anoniman>false</Autor_anoniman>
    </Autor>
    <Punomocnik>
        <Ime>Ime2</Ime>
        <Prezime>Prezime2</Prezime>
        <Adresa>
            <Ulica>Ulica2</Ulica>
            <Broj>50</Broj>
            <Mesto>Mesto2</Mesto>
            <Postanski_broj>25500</Postanski_broj>
        </Adresa>
    </Punomocnik>
    <Delo>
        <Naslov_dela>Naslov_dela0</Naslov_dela>
        <Alternativni_naslov>Alternativni_naslov0</Alternativni_naslov>
        <Delo_prerade>
            <Naslov_izvornog_dela>Naslov_izvornog_dela0</Naslov_izvornog_dela>
            <Autor>
                <Lice>
                    <Adresa>
                        <Ulica>Ulica3</Ulica>
                        <Broj>50</Broj>
                        <Mesto>Mesto3</Mesto>
                        <Postanski_broj>25500</Postanski_broj>
                    </Adresa>
                    <Kontakt>
                    </Kontakt>
                    <Ime>Ime3</Ime>
                    <Prezime>Prezime3</Prezime>
                    <Drzavljanstvo>Drzavljanstvo2</Drzavljanstvo>
                </Lice>
                <Pseudonim_autora>Pseudonim_autora1</Pseudonim_autora>
                <Godina_smrti>2006</Godina_smrti>
                <Autor_anoniman>false</Autor_anoniman>
            </Autor>
        </Delo_prerade>
        <Vrsta_autorskog_dela>Vrsta_autorskog_dela0</Vrsta_autorskog_dela>
        <Forma_zapisa>Forma_zapisa0</Forma_zapisa>
        <Delo_stvoreno_u_radnom_odnosu>false</Delo_stvoreno_u_radnom_odnosu>
        <Nacin_koriscenja_dela>Nacin_koriscenja_dela0</Nacin_koriscenja_dela>
    </Delo>
    <Popunjava_zavod>
        <Opis_dela>Opis_dela0</Opis_dela>
        <Broj_prijave>Broj_prijave0</Broj_prijave>
        <Datum_podnosenja>2006-05-04</Datum_podnosenja>
    </Popunjava_zavod>
</Zahtev>
