=== kumara0230/XML-PROJEKAT-TIM15/back/z1/src/main/resources/xsd/Z1_Schema1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://www.ftn.uns.ac.rs/z1" xmlns:z1="http://www.ftn.uns.ac.rs/z1">
    <xs:element name="Zahtev_za_priznanje_ziga">
        <xs:complexType>
            <xs:sequence>
                <xs:sequence>
                    <xs:element ref="z1:Podaci_o_podnosiocu_prijave"> </xs:element>
                    <xs:element ref="z1:Podaci_o_punomocniku"> </xs:element>
                    <xs:element ref="z1:Podaci_o_zajednickom_predstavniku"> </xs:element>
                    <xs:element ref="z1:Prijava_se_podnosi_za"> </xs:element>
                    <xs:element name="Naznacenje_boje" type="xs:string"/>
                    <xs:element name="Transliteracija_znaka" type="xs:string" minOccurs="0"/>
                    <xs:element name="Prevod_znaka" type="xs:string" minOccurs="0"/>
                    <xs:element name="Opis_znaka" type="xs:string"/>
                    <xs:element name="Nicanska_klasifikacija">
                        <xs:simpleType>
                            <xs:restriction base="xs:positiveInteger">
                                <xs:maxInclusive value="45"/>
                                <xs:minInclusive value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="Zatrazeno_pravo_prvenstva_i_osnov" type="xs:string"/>
                    <xs:element ref="z1:Takse_placene_u_dinarima"> </xs:element>
                </xs:sequence>
                <xs:element ref="z1:Popunjava_zavod"> </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="z1:TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                    <xs:element name="drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="z1:Adresa"/>
            <xs:element ref="z1:Kontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" name="Ulica" type="xs:string"/>
                <xs:element minOccurs="1" name="Ulicni_broj" type="xs:positiveInteger"/>
                <xs:element minOccurs="1" name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:minInclusive value="11000"/>
                            <xs:maxInclusive value="40000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="1" name="Mesto" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Kontakt">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Email" type="xs:string"/>
                <xs:element minOccurs="0" name="Telefon" type="xs:string"/>
                <xs:element minOccurs="0" name="Faks" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Popunjava_podnosioc">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podaci_o_podnosiocu_prijave" type="z1:TFizicko_lice"> </xs:element>
                <xs:element name="Podaci_o_punomocniku" type="z1:TFizicko_lice"> </xs:element>
                <xs:element name="Podaci_o_zajednickom_predstavniku" type="z1:TFizicko_lice"> </xs:element>
                <xs:element ref="z1:Prijava_se_podnosi_za"> </xs:element>
                <xs:element name="Naznacenje_boje" type="xs:string"/>
                <xs:element name="Transliteracija_znaka" type="xs:string" minOccurs="0"/>
                <xs:element name="Prevod_znaka" type="xs:string" minOccurs="0"/>
                <xs:element name="Opis_znaka" type="xs:string"/>
                <xs:element name="Nicanska_klasifikacija">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:maxInclusive value="45"/>
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Zatrazeno_pravo_prvenstva_i_osnov" type="xs:string"/>
                <xs:element ref="z1:Takse_placene_u_dinarima"> </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Prijava_se_podnosi_za">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Vrsta_ziga">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Individualni zig"/>
                            <xs:enumeration value="Kolektivni zig"/>
                            <xs:enumeration value="Zig garancije"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Vrsta_znaka">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Verbalni znak"/>
                            <xs:enumeration value="Graficki znak"/>
                            <xs:enumeration value="Kombinovani znak"/>
                            <xs:whiteSpace value="preserve"/>
                            <xs:enumeration value="Trodimenzionalni znak"/>
                            <xs:enumeration value="Druga vrsta znaka"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Izgled_znaka"> </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Takse_placene_u_dinarima">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Osnovna_taksa" type="xs:positiveInteger"/>
                <xs:element name="Za_odredjenu_klasu" type="xs:positiveInteger"/>
                <xs:element name="Za_graficko_resenje" type="xs:positiveInteger"/>
                <xs:element name="Ukupno" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Popunjava_zavod">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="z1:Priklozi_uz_zahtev"> </xs:element>
                <xs:element name="Broj_prijave_ziga" type="xs:string"/>
                <xs:element name="Datum_podnosenja" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Priklozi_uz_zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Primerak_znaka" default="false">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Spisak_robe_i_usluga" default="false">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Punomocje" default="false">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Generalno_punomocje_ranije_prilozeno" default="false">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Punomocje_ce_biti_naknadno_dostavljeno" default="false">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Opsti_akt_o_kolektivnom_zigu_garancije" default="false">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Dokaz_o_pravu_prvenstva" default="false">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Dokaz_o_uplati_takse" default="false">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPravno_Lice">
        <xs:complexContent>
            <xs:extension base="z1:TLice">
                <xs:sequence>
                    <xs:element name="Poslovno_ime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="Podaci_o_podnosiocu_prijave" type="z1:TLice"> </xs:element>
    <xs:element name="Podaci_o_punomocniku" type="z1:TLice"> </xs:element>
    <xs:element name="Podaci_o_zajednickom_predstavniku" type="z1:TLice"> </xs:element>
</xs:schema>

=== kumara0230/XML-PROJEKAT-TIM15/back/z1/data/z1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_priznanje_ziga xmlns="http://www.ftn.uns.ac.rs/z1"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:schemaLocation="http://www.ftn.uns.ac.rs/z1 file:/D:/Desktop/7_semestar/XWS/Projekat/XML-PROJEKAT-TIM15/Z1_Schema1.xsd">
    <Podaci_o_podnosiocu_prijave xsi:type="TFizicko_lice">
        <Adresa>
            <Ulica>Dr. Sime Milosevica</Ulica>
            <Ulicni_broj>10</Ulicni_broj>
            <Postanski_broj>11000</Postanski_broj>
            <Mesto>Novi Sad</Mesto>
        </Adresa>
        <Kontakt>
            <Email>rakovic.sw45.2019@uns.ac.rs</Email>
            <Telefon>0651231231</Telefon>
            <Faks>021-021-021</Faks>
        </Kontakt>
        <ime>Nenad</ime>
        <prezime>Rakovic</prezime>
        <drzavljanstvo>Srpsko</drzavljanstvo>
    </Podaci_o_podnosiocu_prijave>
    <Podaci_o_punomocniku xsi:type="TFizicko_lice">
        <Adresa>
            <Ulica>Dr. Sime Milosevica</Ulica>
            <Ulicni_broj>11</Ulicni_broj>
            <Postanski_broj>11000</Postanski_broj>
            <Mesto>Novi Sad</Mesto>
        </Adresa>
        <Kontakt>
            <Email>petar.petrovic@gmail.com</Email>
            <Telefon>0651231232</Telefon>
            <Faks>022-022-022</Faks>
        </Kontakt>
        <ime>Petar</ime>
        <prezime>Petrovic</prezime>
        <drzavljanstvo>Srpsko</drzavljanstvo>
    </Podaci_o_punomocniku>
    <Podaci_o_zajednickom_predstavniku xsi:type="TFizicko_lice">
        <Adresa>
            <Ulica>Dr. Sime Milosevica</Ulica>
            <Ulicni_broj>12</Ulicni_broj>
            <Postanski_broj>11000</Postanski_broj>
            <Mesto>Novi Sad</Mesto>
        </Adresa>
        <Kontakt>
            <Email>mika.mikic@gmail.com</Email>
            <Telefon>0651231233</Telefon>
            <Faks>023-023-023</Faks>
        </Kontakt>
        <ime>Mika</ime>
        <prezime>Mikic</prezime>
        <drzavljanstvo>Srpsko</drzavljanstvo>
    </Podaci_o_zajednickom_predstavniku>
    <Prijava_se_podnosi_za>
        <Vrsta_ziga>Individualni zig</Vrsta_ziga>
        <Vrsta_znaka>Graficki znak</Vrsta_znaka>
        <Izgled_znaka></Izgled_znaka>
    </Prijava_se_podnosi_za>
    <Naznacenje_boje>Tamno plava</Naznacenje_boje>
    <Transliteracija_znaka></Transliteracija_znaka>
    <Prevod_znaka></Prevod_znaka>
    <Opis_znaka>Opis znaka</Opis_znaka>
    <Nicanska_klasifikacija>10</Nicanska_klasifikacija>
    <Zatrazeno_pravo_prvenstva_i_osnov>Nema pravo prvenstva</Zatrazeno_pravo_prvenstva_i_osnov>
    <Takse_placene_u_dinarima>
        <Osnovna_taksa>1000</Osnovna_taksa>
        <Za_odredjenu_klasu>1000</Za_odredjenu_klasu>
        <Za_graficko_resenje>1000</Za_graficko_resenje>
        <Ukupno>3000</Ukupno>
    </Takse_placene_u_dinarima>
    <Popunjava_zavod>
        <Priklozi_uz_zahtev>
            <Primerak_znaka>true</Primerak_znaka>
            <Spisak_robe_i_usluga>true</Spisak_robe_i_usluga>
            <Punomocje>true</Punomocje>
            <Generalno_punomocje_ranije_prilozeno>false</Generalno_punomocje_ranije_prilozeno>
            <Punomocje_ce_biti_naknadno_dostavljeno>false</Punomocje_ce_biti_naknadno_dostavljeno>
            <Opsti_akt_o_kolektivnom_zigu_garancije>true</Opsti_akt_o_kolektivnom_zigu_garancije>
            <Dokaz_o_pravu_prvenstva>false</Dokaz_o_pravu_prvenstva>
            <Dokaz_o_uplati_takse>true</Dokaz_o_uplati_takse>
        </Priklozi_uz_zahtev>
        <Broj_prijave_ziga>Z-1234/22</Broj_prijave_ziga>
        <Datum_podnosenja>2022-10-12</Datum_podnosenja>
    </Popunjava_zavod>
</Zahtev_za_priznanje_ziga>
