=== kumara0230/XML-PROJEKAT-TIM15/back/p1/data/p1schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="p1ns" xmlns:p1="p1ns">
    <xs:element name="Zahtev_za_priznanje_patenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="p1:Popunjava_zavod"> </xs:element>
                <xs:element ref="p1:Naziv_pronalaska"> </xs:element>
                <xs:element ref="p1:Podnosilac_prijave"> </xs:element>
                <xs:element minOccurs="0" ref="p1:Pronalazac_patenta"> </xs:element>
                <xs:element ref="p1:Predstavnik_patenta"> </xs:element>
                <xs:element ref="p1:Dostavljanje"> </xs:element>
                <xs:element ref="p1:Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Popunjava_zavod">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Broj_prijave" type="xs:string"/>
                <xs:element name="Datum_prijema" type="xs:date"/>
                <xs:element name="Priznati_datum_podnosenja" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Naziv_pronalaska">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Naziv_pronalaska_na_srpskom" type="xs:string"/>
                <xs:element name="Naziv_pronalaska_na_engleskom" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podnosilac_prijave">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="p1:Podaci_o_licu"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Pronalazac_patenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="p1:Podaci_o_licu"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Predstavnik_patenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="p1:Podaci_o_licu"/>
                <xs:element name="Punomocnik" nillable="true">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="zastupanje"/>
                            <xs:enumeration value="prijem_pismena"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Zajednicki_predstavnik" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Dostavljanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="p1:Adresa"/>
                <xs:element name="Dostavljanje_elektronskim_putem" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0"
                    ref="p1:Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava"> </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Datum_podnosenja_ranije_prijave" type="xs:date"/>
                <xs:element name="Broj_ranije_prijave" type="xs:string"/>
                <xs:element name="Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije"
                    type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="p1:Adresa"/>
            <xs:element ref="p1:Kontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="p1:TLice"> </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="p1:TLice">
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime" type="xs:string"/>
                    <xs:element name="Drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="Kontakt">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Telefon" type="xs:string"/>
                <xs:element minOccurs="0" name="Faks" type="xs:string"/>
                <xs:element minOccurs="0" name="Email" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj" type="xs:positiveInteger"/>
                <xs:element name="Mesto" type="xs:string"/>
                <xs:element name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="11000"/>
                            <xs:maxInclusive value="40000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podaci_o_licu" type="p1:TLice"/>
</xs:schema>

=== kumara0230/XML-PROJEKAT-TIM15/back/p1/src/main/resources/xsd/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_priznanje_patenta xmlns="http://ftn.uns.ac.rs/p1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/p1 file:/C:/Users/LAZAR/Desktop/XML_i_web_servisi/Projekat/Projekat/XML-PROJEKAT-TIM15/back/p1/src/main/resources/xsd/p1schema.xsd">
    <Popunjava_zavod>
        <Broj_prijave>Broj_prijave0</Broj_prijave>
        <Datum_prijema>2006-05-04</Datum_prijema>
        <Priznati_datum_podnosenja>2006-05-04</Priznati_datum_podnosenja>
    </Popunjava_zavod>
    <Naziv_pronalaska>
        <Naziv_pronalaska_na_srpskom>Naziv_pronalaska_na_srpskom0</Naziv_pronalaska_na_srpskom>
        <Naziv_pronalaska_na_engleskom>Naziv_pronalaska_na_engleskom0</Naziv_pronalaska_na_engleskom>
    </Naziv_pronalaska>
    <Podnosilac_prijave>
        <Podaci_o_licu xmlns:p1="http://ftn.uns.ac.rs/p1" xsi:type="p1:TFizicko_lice">
            <Adresa>
                <Ulica>Ulica0</Ulica>
                <Broj>50</Broj>
                <Mesto>Mesto0</Mesto>
                <Postanski_broj>25500</Postanski_broj>
            </Adresa>
            <Kontakt>
                <Telefon>Telefon0</Telefon>
                <Faks>Faks0</Faks>
                <Email>Email0</Email>
            </Kontakt>
            <Ime>Ime0</Ime>
            <Prezime>Prezime0</Prezime>
            <Drzavljanstvo>Drzavljanstvo0</Drzavljanstvo>
        </Podaci_o_licu>
    </Podnosilac_prijave>
    <Pronalazac_patenta>
        <Podaci_o_licu xmlns:p1="http://ftn.uns.ac.rs/p1" xsi:type="p1:TFizicko_lice">
            <Adresa>
                <Ulica>Ulica1</Ulica>
                <Broj>50</Broj>
                <Mesto>Mesto1</Mesto>
                <Postanski_broj>25500</Postanski_broj>
            </Adresa>
            <Kontakt>
                <Telefon>Telefon1</Telefon>
                <Faks>Faks1</Faks>
                <Email>Email1</Email>
            </Kontakt>
            <Ime>Ime1</Ime>
            <Prezime>Prezime1</Prezime>
            <Drzavljanstvo>Drzavljanstvo1</Drzavljanstvo>
        </Podaci_o_licu>
    </Pronalazac_patenta>
    <Predstavnik_patenta>
        <Podaci_o_licu xmlns:p1="http://ftn.uns.ac.rs/p1" xsi:type="p1:TFizicko_lice">
            <Adresa>
                <Ulica>Ulica2</Ulica>
                <Broj>50</Broj>
                <Mesto>Mesto2</Mesto>
                <Postanski_broj>25500</Postanski_broj>
            </Adresa>
            <Kontakt>
                <Telefon>Telefon2</Telefon>
                <Faks>Faks2</Faks>
                <Email>Email2</Email>
            </Kontakt>
            <Ime>Ime2</Ime>
            <Prezime>Prezime2</Prezime>
            <Drzavljanstvo>Drzavljanstvo2</Drzavljanstvo>
        </Podaci_o_licu>
        <Punomocnik>zastupanje</Punomocnik>
        <Zajednicki_predstavnik>false</Zajednicki_predstavnik>
    </Predstavnik_patenta>
    <Dostavljanje>
        <Adresa>
            <Ulica>Ulica3</Ulica>
            <Broj>50</Broj>
            <Mesto>Mesto3</Mesto>
            <Postanski_broj>25500</Postanski_broj>
        </Adresa>
        <Dostavljanje_elektronskim_putem>false</Dostavljanje_elektronskim_putem>
    </Dostavljanje>
    <Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
        <Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
            <Datum_podnosenja_ranije_prijave>2006-05-04</Datum_podnosenja_ranije_prijave>
            <Broj_ranije_prijave>Broj_ranije_prijave0</Broj_ranije_prijave>
            <Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije>Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije0</Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije>
        </Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
        <Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
            <Datum_podnosenja_ranije_prijave>2006-05-04</Datum_podnosenja_ranije_prijave>
            <Broj_ranije_prijave>Broj_ranije_prijave1</Broj_ranije_prijave>
            <Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije>Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije1</Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije>
        </Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
    </Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
</Zahtev_za_priznanje_patenta>

=== kumara0230/XML-PROJEKAT-TIM15/back/p1/src/main/resources/xsd/p1_popunjen.xml
<?xml version="1.0" encoding="UTF-8"?>
<p1:Zahtev_za_priznanje_patenta xmlns="http://ftn.uns.ac.rs/p1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:p1="http://ftn.uns.ac.rs/p1"
 xsi:schemaLocation="http://ftn.uns.ac.rs/p1 p1schema.xsd">
    <p1:Popunjava_zavod>
        <p1:Broj_prijave>P-1</p1:Broj_prijave>
        <p1:Datum_prijema>2023-09-13</p1:Datum_prijema>
        <p1:Priznati_datum_podnosenja>2023-09-13</p1:Priznati_datum_podnosenja>
    </p1:Popunjava_zavod>
    <p1:Naziv_pronalaska>
        <p1:Naziv_pronalaska_na_srpskom>Patent o patentu</p1:Naziv_pronalaska_na_srpskom>
        <p1:Naziv_pronalaska_na_engleskom>Pattent of pattent</p1:Naziv_pronalaska_na_engleskom>
    </p1:Naziv_pronalaska>
    <p1:Podnosilac_prijave>
        <p1:Podaci_o_licu xsi:type="p1:TFizicko_lice">
            <p1:Adresa>
                <p1:Ulica>Jevrejska</p1:Ulica>
                <p1:Broj>23</p1:Broj>
                <p1:Mesto>Novi Sad</p1:Mesto>
                <p1:Postanski_broj>21000</p1:Postanski_broj>
            </p1:Adresa>
            <p1:Kontakt>
                <p1:Telefon>021450810</p1:Telefon>
                <p1:Faks>021458133</p1:Faks>
                <p1:Email>emailneki1@gmail.com</p1:Email>
            </p1:Kontakt>
            <p1:Ime>Pera</p1:Ime>
            <p1:Prezime>Peric</p1:Prezime>
            <p1:Drzavljanstvo>Srpsko</p1:Drzavljanstvo>
        </p1:Podaci_o_licu>
    </p1:Podnosilac_prijave>
    <p1:Pronalazac_patenta>
        <p1:Podaci_o_licu xsi:type="p1:TFizicko_lice">
            <p1:Adresa>
                <p1:Ulica>Bulevar Mihajla Pupina</p1:Ulica>
                <p1:Broj>23</p1:Broj>
                <p1:Mesto>Novi Sad</p1:Mesto>
                <p1:Postanski_broj>21000</p1:Postanski_broj>
            </p1:Adresa>
            <p1:Kontakt>
                <p1:Telefon>021450810</p1:Telefon>
                <p1:Faks>021458133</p1:Faks>
                <p1:Email>emailneki2@gmail.com</p1:Email>
            </p1:Kontakt>
            <p1:Ime>Mika</p1:Ime>
            <p1:Prezime>Mikic</p1:Prezime>
            <p1:Drzavljanstvo>Srpsko</p1:Drzavljanstvo>
        </p1:Podaci_o_licu>
    </p1:Pronalazac_patenta>
    <p1:Predstavnik_patenta>
        <p1:Podaci_o_licu xsi:type="p1:TFizicko_lice">
            <p1:Adresa>
                <p1:Ulica>Trg Dositeja Obradovica</p1:Ulica>
                <p1:Broj>3</p1:Broj>
                <p1:Mesto></p1:Mesto>
                <p1:Postanski_broj>21000</p1:Postanski_broj>
            </p1:Adresa>
            <p1:Kontakt>
                <p1:Telefon>021450810</p1:Telefon>
                <p1:Faks>021458133</p1:Faks>
                <p1:Email>emailneki3@gmail.com</p1:Email>
            </p1:Kontakt>
            <p1:Ime>Zika</p1:Ime>
            <p1:Prezime>Pavlovic</p1:Prezime>
            <p1:Drzavljanstvo>Srpsko</p1:Drzavljanstvo>
        </p1:Podaci_o_licu>
        <p1:Punomocnik>zastupanje</p1:Punomocnik>
        <p1:Zajednicki_predstavnik>true</p1:Zajednicki_predstavnik>
    </p1:Predstavnik_patenta>
    <p1:Dostavljanje>
        <p1:Adresa>
            <p1:Ulica>Bulevar Oslobodjenja</p1:Ulica>
            <p1:Broj>23</p1:Broj>
            <p1:Mesto>Novi Sad</p1:Mesto>
            <p1:Postanski_broj>21000</p1:Postanski_broj>
        </p1:Adresa>
        <p1:Dostavljanje_elektronskim_putem>true</p1:Dostavljanje_elektronskim_putem>
    </p1:Dostavljanje>
    <p1:Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
        <p1:Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
            <p1:Datum_podnosenja_ranije_prijave>2023-09-13</p1:Datum_podnosenja_ranije_prijave>
            <p1:Broj_ranije_prijave>I-1</p1:Broj_ranije_prijave>
            <p1:Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije>RS</p1:Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije>
        </p1:Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
    </p1:Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
</p1:Zahtev_za_priznanje_patenta>

=== kumara0230/XML-PROJEKAT-TIM15/back/p1/data/p1_popunjen.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_priznanje_patenta xmlns="p1ns"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="p1ns p1schema.xsd">
    <Popunjava_zavod>
        <Broj_prijave>P-1</Broj_prijave>
        <Datum_prijema>2023-09-13</Datum_prijema>
        <Priznati_datum_podnosenja>2023-09-13</Priznati_datum_podnosenja>
    </Popunjava_zavod>
    <Naziv_pronalaska>
        <Naziv_pronalaska_na_srpskom>Patent o patentu</Naziv_pronalaska_na_srpskom>
        <Naziv_pronalaska_na_engleskom>Pattent of pattent</Naziv_pronalaska_na_engleskom>
    </Naziv_pronalaska>
    <Podnosilac_prijave>
        <Podaci_o_licu xmlns:p1="p1ns" xsi:type="p1:TFizicko_lice">
            <Adresa>
                <Ulica>Jevrejska</Ulica>
                <Broj>23</Broj>
                <Mesto>Novi Sad</Mesto>
                <Postanski_broj>21000</Postanski_broj>
            </Adresa>
            <Kontakt>
                <Telefon>021450810</Telefon>
                <Faks>021458133</Faks>
                <Email>emailneki1@gmail.com</Email>
            </Kontakt>
            <Ime>Pera</Ime>
            <Prezime>Peric</Prezime>
            <Drzavljanstvo>Srpsko</Drzavljanstvo>
        </Podaci_o_licu>
    </Podnosilac_prijave>
    <Pronalazac_patenta>
        <Podaci_o_licu xmlns:p1="p1ns" xsi:type="p1:TFizicko_lice">
            <Adresa>
                <Ulica>Bulevar Mihajla Pupina</Ulica>
                <Broj>23</Broj>
                <Mesto>Novi Sad</Mesto>
                <Postanski_broj>21000</Postanski_broj>
            </Adresa>
            <Kontakt>
                <Telefon>021450810</Telefon>
                <Faks>021458133</Faks>
                <Email>emailneki2@gmail.com</Email>
            </Kontakt>
            <Ime>Mika</Ime>
            <Prezime>Mikic</Prezime>
            <Drzavljanstvo>Srpsko</Drzavljanstvo>
        </Podaci_o_licu>
    </Pronalazac_patenta>
    <Predstavnik_patenta>
        <Podaci_o_licu xmlns:p1="p1ns" xsi:type="p1:TFizicko_lice">
            <Adresa>
                <Ulica>Trg Dositeja Obradovica</Ulica>
                <Broj>3</Broj>
                <Mesto></Mesto>
                <Postanski_broj>21000</Postanski_broj>
            </Adresa>
            <Kontakt>
                <Telefon>021450810</Telefon>
                <Faks>021458133</Faks>
                <Email>emailneki3@gmail.com</Email>
            </Kontakt>
            <Ime>Zika</Ime>
            <Prezime>Pavlovic</Prezime>
            <Drzavljanstvo>Srpsko</Drzavljanstvo>
        </Podaci_o_licu>
        <Punomocnik>zastupanje</Punomocnik>
        <Zajednicki_predstavnik>true</Zajednicki_predstavnik>
    </Predstavnik_patenta>
    <Dostavljanje>
        <Adresa>
            <Ulica>Bulevar Oslobodjenja</Ulica>
            <Broj>23</Broj>
            <Mesto>Novi Sad</Mesto>
            <Postanski_broj>21000</Postanski_broj>
        </Adresa>
        <Dostavljanje_elektronskim_putem>true</Dostavljanje_elektronskim_putem>
    </Dostavljanje>
    <Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
        <Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
            <Datum_podnosenja_ranije_prijave>2023-09-13</Datum_podnosenja_ranije_prijave>
            <Broj_ranije_prijave>I-1</Broj_ranije_prijave>
            <Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije>RS</Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije>
        </Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
    </Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
</Zahtev_za_priznanje_patenta>
